project:
  type: website
  output-dir: docs

website:
  title: "LORENA ZAMORA"
  navbar:
    left:
      - text: ¡Hola!
        file: about.qmd
      - index.qmd
      - CV.qmd
      - icon: linkedin
        href: https://www.linkedin.com/
      - icon: instagram
        href: https://instagram.com/
format:
  html:
    theme: morp
    css: styles.css

editor: visual

