project:
  type: website
  output-dir: docs

website:
  title: "LORENA ZAMORA"
  navbar:
    left:
      - about.qmd
      - index.qmd
      - CV.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com/
format:
  html:
    theme: morp
    css: styles.css

editor: visual

