# Currículum vitae {style="color:blue"}

## EXPERIENCIA LABORAL {style="color: black"}

**Ayudante de peluquería en WALTER PELUQUEROS**

**15/09/2019 – 21/01/2021**

**Valencia-España**

-   Decoloraciones

-   Tratamientos para tinte de cabello

-   Acondicionamiento capilar

-   Recuperación de cabello maltratado

-   Asesoría de imagen personal

## EDUCACIÓN Y FORMACIÓN

**TÉCNICA SUPERIOR EN ASESORÍA DE IMAGEN PERSONAL Y CORPORATIVA:** TEVIAN - ESCUELA DE ESTÉTICA Y PELUQUERÍA. Período: 15/09/2019 – 21/01/2021

**Campo de estudio:**

-   Diseño de imagen personal

<!-- -->

-   Estilismo en vestuario y complementos

<!-- -->

-   Asesoría en cosmética

<!-- -->

-   Protocolo y organización de eventos

<!-- -->

-   Habilidades comunicativas

<!-- -->

-   Asesoría de peluquería

<!-- -->

-   Usos sociales

<!-- -->

-   Dirección y comercialización

**GRADO MEDIO EN PELUQUERÍA Y ESTÉTICA CAPILAR**: TEVIAN - ESCUELA DE ESTÉTICA Y PELUQUERÍA. VALENCIA, España. Período: 15/10/205 - 28/06/2018

**Campo de estudio:**

-   Cosmética para peluquería

-   Análisis capilar

-   Coloración capilar

-   Peinados y recogidos

<!-- -->

-   Estética de manos y pies

<!-- -->

-   Técnicas de corte de cabello

<!-- -->

-   Cambios de formas permanente del cabello

<!-- -->

-   Peluquería y estilismo

<!-- -->

-   Marketing y venta en imagen personal

## **COMPETENCIAS DIGITALES**

-   Office 365

-   Canva

-   Redes sociales: LinkedIn

-   Internet: Google Crome

## **INFORMACIÓN ADICIONAL**

-   Permiso de conducción: B1
